#@TYPE: Machine
#@NAME: Raspberry Pi Compute Module 4 IO Board (64-bit)
#@DESCRIPTION: Machine configuration for the Raspberry Pi Compute Module 4 IO Board in 64 bits mode

MACHINEOVERRIDES =. "raspberrypi4-64:"

include conf/machine/raspberrypi4-64.conf

# Enable USB ports on I/O board via /boot/config.txt
RPI_EXTRA_CONFIG:append = " \n\
dtoverlay=dwc2,dr_mode=host\n\
"
