#@TYPE: Machine
#@NAME: Raspberry Pi Compute Module 4 LDO Positron Board (64-bit)
#@DESCRIPTION: Machine configuration for the Raspberry Pi Compute Module 4 LDO Positron Board in 64 bits mode

MACHINEOVERRIDES =. "raspberrypi4-64:"

include conf/machine/raspberrypi4-64.conf

# Enable various things via /boot/config.txt
# FIXME - not sure what is needed but seeing crap on screen now
RPI_EXTRA_CONFIG = " \n\
dtparam=audio=on\n\
camera_auto_detect=1\n\
display_auto_detect=1\n\
max_framebuffers=2\n\
disable_overscan=1\n\
[cm4]\n\
otg_mode=1\n\
[pi4]\n\
arm_boost=1\n\
[all]\n\
disable_splash=1\n\
gpio=0-9=a2\n\
gpio=12-17=a2\n\
gpio=20-25=a2\n\
dtoverlay=dpi18\n\
enable_dpi_lcd=1\n\
display_default_lcd=1\n\
extra_transpose_buffer=2\n\
dpi_group=2\n\
dpi_mode=87\n\
dpi_output_format=0x6f006\n\
hdmi_timings=640 0 20 10 10 480 0 10 5 5 0 0 0 60 0 60000000 1\n\
dtoverlay=ldo_35dpi_3b4b.dtbo\n\
dtoverlay=ldo_35dpi_3b.dtbo\n\
dtoverlay=ldo_35dpi_4b.dtbo\n\
display_lcd_rotate=2\n\
"

VC4DTBO = ""
