#@TYPE: Machine
#@NAME: Raspberry Pi Compute Module 4 LDO Positron Board (64-bit)
#@DESCRIPTION: Machine configuration for the Raspberry Pi Compute Module 4 LDO Positron Board in 64 bits mode

MACHINEOVERRIDES =. "raspberrypi4-64:"

include conf/machine/raspberrypi4-64.conf

# Enable various things via /boot/config.txt
# FIXME - not sure what is needed but seeing crap on screen now
RPI_EXTRA_CONFIG = "\
gpio=0-9=a2\n\
gpio=12-17=a2\n\
gpio=20-25=a2\n\
enable_dpi_lcd=1\n\
display_default_lcd=1\n\
dpi_group=2\n\
dpi_mode=87\n\
dpi_output_format=0x6f006\n\
hdmi_timings=640 0 20 10 10 480 0 10 5 5 0 0 0 60 0 60000000 1\n\
dtoverlay=dpi18\n\
dtoverlay=ldo_35dpi_3b4b\n\
dtoverlay=ldo_35dpi_3b\n\
display_lcd_rotate=2\n\
"

RPI_EXTRA_CONFIG:append = "display_auto_detect=1\n"

# Enable device to work in USB host mode
RPI_EXTRA_CONFIG:append = "otg_mode=1\n"

VC4DTBO = ""
DISABLE_OVERSCAN = "1"
DISABLE_SPLASH = "1"

XSERVER:append = " xf86-video-fbdev"
ENABLE_I2C = "1"
# ENABLE_I2C = "1" adds dtparam=i2c_arm=on, which breaks touch due to dt conflict

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " overlays/dpi18.dtbo"

IMAGE_INSTALL:append = " ldo-overlays"
